import { useLocation } from "react-router-dom";
import { useState } from "react";
import { motion } from "framer-motion";
import { PiBookOpenBold } from "react-icons/pi";

function ResultPage() {
  const { state } = useLocation();
  const data = state?.data || state;

  const [openIndex, setOpenIndex] = useState(null);
  const [completedSections, setCompletedSections] = useState([]);

  if (!data) return <div className="text-center mt-20">No Data</div>;

  const totalSections = data.sections?.length || 0;

  // 🎯 Progress Logic
  const progress =
    ((completedSections.length +
      (openIndex !== null && !completedSections.includes(openIndex) ? 1 : 0)) /
      totalSections) *
    100;

  const handleToggle = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const markComplete = (index) => {
    if (!completedSections.includes(index)) {
      setCompletedSections([...completedSections, index]);
    }
  };

  // 🎨 COLORS ARRAY
  const colors = [
    {
      border: "border-blue-400",
      bg: "bg-blue-50",
      badge: "bg-blue-500",
    },
    {
      border: "border-green-400",
      bg: "bg-green-50",
      badge: "bg-green-500",
    },
    {
      border: "border-yellow-400",
      bg: "bg-yellow-50",
      badge: "bg-yellow-500",
    },
    {
      border: "border-purple-400",
      bg: "bg-purple-50",
      badge: "bg-purple-500",
    },
    {
      border: "border-pink-400",
      bg: "bg-pink-50",
      badge: "bg-pink-500",
    },
  ];

  return (
    <div className="min-h-screen bg-gray-100 px-6 py-10">

      {/* HEADER */}
      <div className="max-w-5xl mx-auto bg-white p-6 rounded-2xl shadow flex gap-5 items-center">
        <div className="w-16 h-16 bg-indigo-100 rounded-xl flex items-center justify-center text-xl">
          <PiBookOpenBold />
        </div>

        <div>
          <h1 className="text-2xl font-semibold">{data?.topic}</h1>
          <p className="text-gray-500 text-sm">
            Course generated by <span className="font-bold">Course Crush</span> AI
          </p>

          <div className="flex gap-3 mt-3 flex-wrap">
            <span className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm">
              🌐 {data?.language}
            </span>
            <span className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm">
              📊 {data?.level}
            </span>
          </div>
        </div>
      </div>

      {/* PROGRESS */}
      <div className="max-w-5xl mx-auto mt-6 bg-white p-4 rounded-xl shadow">
        <div className="flex justify-between text-sm mb-2">
          <span>Course Progress</span>
          <span>{Math.round(progress)}%</span>
        </div>

        <div className="w-full h-2 bg-gray-200 rounded-full">
          <div
            className="h-2 bg-blue-500 rounded-full transition-all duration-300"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      {/* SECTIONS */}
      <div className="max-w-5xl mx-auto mt-6 space-y-4">
        {data?.sections?.map((section, index) => {
          const isOpen = openIndex === index;
          const isCompleted = completedSections.includes(index);

          const color = colors[index % colors.length];

          return (
            <div
              key={index}
              className={`rounded-xl shadow border-l-4 ${color.border} ${color.bg}`}
            >

              {/* HEADER */}
              <div
                onClick={() => handleToggle(index)}
                className="flex justify-between items-center px-5 py-4 cursor-pointer"
              >
                <div className="flex gap-3 items-center">
                  <span
                    className={`w-7 h-7 text-white flex items-center justify-center rounded-full text-sm ${color.badge}`}
                  >
                    {index + 1}
                  </span>

                  <h2 className="font-medium">{section?.heading}</h2>

                  {isCompleted && (
                    <span className="text-green-600 text-xs font-semibold">
                      ✔ Completed
                    </span>
                  )}
                </div>

                <span>{isOpen ? "▲" : "▼"}</span>
              </div>

              {/* CONTENT */}
              {isOpen && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="px-6 pb-5"
                >
                  {/* POINTS */}
                  <ul className="list-disc ml-5 space-y-2 text-gray-700">
                    {section?.points?.map((point, i) => (
                      <li key={i}>{point?.text}</li>
                    ))}
                  </ul>

                  {/* EXAMPLE */}
                  {section?.example && (
                    <div className="mt-4 bg-white/70 p-4 rounded-xl">
                      <h3 className="font-semibold mb-2">💡 Example</h3>

                      <p className="text-sm mb-3">
                        {section?.example?.explanation}
                      </p>

                      <div className="bg-black text-green-400 p-4 rounded-lg text-sm overflow-auto">
                        <pre>{section?.example?.code}</pre>
                      </div>
                    </div>
                  )}

                  {/* BUTTON */}
                  <button
                    onClick={() => markComplete(index)}
                    disabled={isCompleted}
                    className={`mt-4 px-4 py-2 rounded-lg text-sm font-medium transition
                      ${
                        isCompleted
                          ? "bg-gray-300 cursor-not-allowed"
                          : "bg-green-500 text-white hover:bg-green-600"
                      }
                    `}
                  >
                    {isCompleted ? "Completed" : "Mark as Complete"}
                  </button>
                </motion.div>
              )}
            </div>
          );
        })}
      </div>
      {completedSections.length === totalSections && totalSections > 0 && (
  <div className="max-w-5xl mx-auto mt-8 text-center">
    
    <button className="
      px-6 py-3
      bg-gradient-to-r from-purple-500 to-indigo-600
      text-white font-semibold
      rounded-xl
      shadow-lg
      hover:scale-105 transition
    ">
    Course Completed
    </button>

  </div>
)}
    </div>
  );
}

export default ResultPage;