import { useLocation, useNavigate } from "react-router-dom";
import { useState } from "react";
import { motion } from "framer-motion";
import { PiBookOpenBold } from "react-icons/pi";
import { FaArrowLeftLong } from "react-icons/fa6";

function ResultPage() {
  const navigate = useNavigate();

  const { state } = useLocation();

  const data = state?.data || state;

  const [openIndex, setOpenIndex] = useState(0);

  const [completedSections, setCompletedSections] = useState([]);

  if (!data) {
    return <div className="text-center mt-20">No Data</div>;
  }

  const totalSections = data.sections?.length || 0;

  const progress =
    ((completedSections.length +
      (openIndex !== null && !completedSections.includes(openIndex) ? 1 : 0)) /
      totalSections) *
    100;

  const markComplete = (index) => {
    if (!completedSections.includes(index)) {
      setCompletedSections([...completedSections, index]);
    }
  };

  // 🎨 COLORS
  const colors = [
    {
      border: "border-blue-400",
      bg: "bg-blue-50",
      badge: "bg-blue-500",
    },
    {
      border: "border-green-400",
      bg: "bg-green-50",
      badge: "bg-green-500",
    },
    {
      border: "border-yellow-400",
      bg: "bg-yellow-50",
      badge: "bg-yellow-500",
    },
    {
      border: "border-purple-400",
      bg: "bg-purple-50",
      badge: "bg-purple-500",
    },
    {
      border: "border-pink-400",
      bg: "bg-pink-50",
      badge: "bg-pink-500",
    },
  ];

  const currentSection = data.sections?.[openIndex];

  const currentColor = colors[openIndex % colors.length];

  return (
    <div className="min-h-screen bg-gray-100 px-4 md:px-6 py-8">
      {/* HEADER */}
      <div className="max-w-7xl mx-auto bg-white p-6 rounded-3xl shadow flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5">
        {/* LEFT */}
        <div className="flex gap-5 items-center">
          <div className="w-16 h-16 bg-indigo-100 rounded-2xl flex items-center justify-center text-2xl">
            <PiBookOpenBold />
          </div>

          <div>
            <h1 className="text-2xl md:text-3xl font-bold">{data?.topic}</h1>

            <p className="text-gray-500 text-sm mt-1">
              Course generated by{" "}
              <span className="font-bold">Course Crush</span> AI
            </p>

            <div className="flex gap-3 mt-3 flex-wrap">
              <span className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm">
                🌐 {data?.language}
              </span>

              <span className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm">
                📊 {data?.level}
              </span>
            </div>
          </div>
        </div>

        {/* RIGHT BUTTON */}
        <button
          onClick={() => navigate("/generate-ai")}
          className="
            flex items-center justify-center gap-2
            px-5 py-3
            rounded-xl
            bg-white
            border
            shadow-sm
            hover:bg-gray-100
            transition
            w-full
            sm:w-fit
          "
        >
          <FaArrowLeftLong className="w-4 h-4" />

          <span className="text-sm font-medium">Back</span>
        </button>
      </div>

      {/* PROGRESS */}
      <div className="max-w-7xl mx-auto mt-6 bg-white p-4 rounded-2xl shadow">
        <div className="flex justify-between text-sm mb-2">
          <span>Course Progress</span>

          <span>{Math.round(progress)}%</span>
        </div>

        <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
          <div
            className="h-2 bg-indigo-500 rounded-full transition-all duration-300"
            style={{
              width: `${progress}%`,
            }}
          />
        </div>
      </div>

      <div className="max-w-7xl mx-auto mt-6 grid lg:grid-cols-[320px_1fr] gap-6">
        {/* ================= MOBILE VIEW ================= */}
        <div className="lg:hidden space-y-4">
          {data?.sections?.map((section, index) => {
            const isOpen = openIndex === index;

            const isCompleted = completedSections.includes(index);

            const color = colors[index % colors.length];

            return (
              <div
                key={index}
                className={`
            rounded-2xl
            shadow
            border-l-4
            bg-white
            overflow-hidden
            ${color.border}
          `}
              >
                {/* HEADER */}
                <button
                  onClick={() => setOpenIndex(isOpen ? null : index)}
                  className="w-full p-4 flex items-center justify-between"
                >
                  <div className="flex items-center gap-3 text-left">
                    <span
                      className={`
                  w-8 h-8
                  rounded-full
                  text-white
                  text-sm
                  flex items-center justify-center
                  ${color.badge}
                `}
                    >
                      {index + 1}
                    </span>

                    <div>
                      <h3 className="font-medium">{section?.heading}</h3>

                      {isCompleted && (
                        <p className="text-xs text-green-600 mt-1 font-medium">
                          ✔ Completed
                        </p>
                      )}
                    </div>
                  </div>

                  <span>{isOpen ? "▲" : "▼"}</span>
                </button>

                {/* CONTENT */}
                {isOpen && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="px-5 pb-5"
                  >
                    {/* POINTS */}
                    <ul className="list-disc ml-5 space-y-3 text-gray-700 leading-relaxed">
                      {section?.points?.map((point, i) => (
                        <li key={i}>{point?.text}</li>
                      ))}
                    </ul>

                    {/* EXAMPLE */}
                    {section?.example && (
                      <div className="mt-6 bg-gray-50 p-4 rounded-2xl border">
                        <h3 className="font-bold mb-3">💡 Example</h3>

                        <p className="text-sm text-gray-700 mb-4">
                          {section?.example?.explanation}
                        </p>

                        <div className="bg-black text-green-400 p-4 rounded-xl text-sm overflow-auto">
                          <pre>{section?.example?.code}</pre>
                        </div>
                      </div>
                    )}

                    {/* COMPLETE BUTTON */}
                    <button
                      onClick={() => markComplete(index)}
                      disabled={isCompleted}
                      className={`
                  mt-6
                  px-5 py-3
                  rounded-xl
                  font-medium
                  transition
                  ${
                    isCompleted
                      ? "bg-gray-300 cursor-not-allowed"
                      : "bg-black text-white hover:bg-green-600"
                  }
                `}
                    >
                      {isCompleted ? "Completed" : "Mark as Complete"}
                    </button>
                  </motion.div>
                )}
              </div>
            );
          })}
        </div>

        {/* ================= DESKTOP VIEW ================= */}
        <>
          {/* SIDEBAR */}
          <div className="hidden lg:block bg-white rounded-3xl shadow p-4 h-fit sticky top-5">
            <h2 className="text-xl font-bold mb-5">Course Sections</h2>

            <div className="space-y-3">
              {data?.sections?.map((section, index) => {
                const isActive = openIndex === index;

                const isCompleted = completedSections.includes(index);

                const color = colors[index % colors.length];

                return (
                  <button
                    key={index}
                    onClick={() => setOpenIndex(index)}
                    className={`
                w-full
                text-left
                p-4
                rounded-2xl
                transition-all
                border
                ${
                  isActive
                    ? `${color.bg} ${color.border} shadow-md`
                    : "bg-gray-50 border-gray-200 hover:bg-gray-100"
                }
              `}
                  >
                    <div className="flex items-center gap-3">
                      <span
                        className={`
                    w-7 h-7
                    rounded-full
                    text-white
                    text-sm
                    flex items-center justify-center
                    ${color.badge}
                  `}
                      >
                        {index + 1}
                      </span>

                      <div className="flex-1">
                        <h3 className="font-medium text-sm">
                          {section?.heading}
                        </h3>

                        {isCompleted && (
                          <p className="text-xs text-green-600 mt-1 font-medium">
                            ✔ Completed
                          </p>
                        )}
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* CONTENT */}
          <motion.div
            key={openIndex}
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            className={`
        hidden lg:block
        rounded-3xl
        shadow
        border-l-4
        p-6 md:p-8
        bg-white
        ${currentColor.border}
      `}
          >
            {/* TITLE */}
            <div className="flex items-center gap-4 mb-6">
              <span
                className={`
            w-10 h-10
            rounded-full
            text-white
            flex items-center justify-center
            font-bold
            ${currentColor.badge}
          `}
              >
                {openIndex + 1}
              </span>

              <h2 className="text-2xl md:text-3xl font-bold">
                {currentSection?.heading}
              </h2>
            </div>

            {/* POINTS */}
            <ul className="list-disc ml-5 space-y-3 text-gray-700 leading-relaxed">
              {currentSection?.points?.map((point, i) => (
                <li key={i}>{point?.text}</li>
              ))}
            </ul>

            {/* EXAMPLE */}
            {currentSection?.example && (
              <div className="mt-8 bg-gray-50 p-5 rounded-2xl border">
                <h3 className="font-bold text-lg mb-3">💡 Example</h3>

                <p className="text-gray-700 text-sm leading-relaxed mb-4">
                  {currentSection?.example?.explanation}
                </p>

                <div className="bg-black text-green-400 p-5 rounded-xl text-sm overflow-auto">
                  <pre>{currentSection?.example?.code}</pre>
                </div>
              </div>
            )}

            {/* BUTTON */}
            <button
              onClick={() => markComplete(openIndex)}
              disabled={completedSections.includes(openIndex)}
              className={`
          mt-8
          px-5 py-3
          rounded-xl
          font-medium
          transition
          ${
            completedSections.includes(openIndex)
              ? "bg-gray-300 cursor-not-allowed"
              : "bg-black text-white hover:bg-green-600"
          }
        `}
            >
              {completedSections.includes(openIndex)
                ? "Completed"
                : "Mark as Complete"}
            </button>
          </motion.div>
        </>
      </div>

      {/* COURSE COMPLETE */}
      {completedSections.length === totalSections && totalSections > 0 && (
        <div className="max-w-7xl mx-auto mt-8 text-center">
          <button onClick={() =>
    navigate("/examboard", {
      state: { courseId: data._id },
    })
  }
            className="
                px-8 py-4
                bg-black
                text-white
                font-semibold
                rounded-2xl
                shadow-lg
                hover:scale-105
                transition
              "
          >
            Take Exam
          </button>
        </div>
      )}
    </div>
  );
}

export default ResultPage;
